volumes:
  mysql: {}
  artemis: {}

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mymakler
      MYSQL_USER: mymakler
      MYSQL_PASSWORD: mymakler
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql:/var/lib/mysql
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.35.0
    container_name: artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - my_network
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - AMQ_SECURITY_ENABLED=false
    volumes:
      - artemis:/opt/activemq/data
  mymakler-svc-api:
    build:
      context: ./mymakler-svc-api
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: my_mysql_container
      MYSQL_PORT: 3306
      MYSQL_DB: mymakler
      MYSQL_USERNAME: mymakler
      MYSQL_PASSWORD: mymakler
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - my_network
    restart: always
  mymakler-ui-web:
    build:
      context: ./mymakler-ui-web
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: my_mysql_container
      MYSQL_PORT: 3306
      MYSQL_DB: mymakler
      MYSQL_USERNAME: mymakler
      MYSQL_PASSWORD: mymakler
      MYMAKLER_SVC_API_URL: http://mymakler-svc-api:8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mymakler-svc-api
    networks:
      - my_network
    restart: always
  mymakler-svc-frauddetection:
    build:
      context: ./mymakler-svc-frauddetection
      dockerfile: Dockerfile
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
      - mymakler-svc-api
    networks:
      - my_network  
    restart: always
    

networks:
  my_network:
    driver: bridge